export const person = [
    {
      name:"Charley", 
      institution:"Unklab", 
      address:"Palu",
      phoneNumber:"08281231238"
    },
    {
      name:"Hurufiah", 
      institution:"Unklab", 
      address:"Palu",
      phoneNumber:"08281231238"
    },
    {
      name:"Abjadiah", 
      institution:"Unklab", 
      address:"Palu",
      phoneNumber:"08281231238"
    },
    {
      name:"Abjadiayah", 
      institution:"Unklab", 
      address:"Palu",
      phoneNumber:"08281231238"
    },
  ]